version: '3'

services:
  nginx:
    container_name: 77sol-nginx
    image: nginx
    ports:
      - '80:80'
    links:
      - app
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    restart: always

  app:
    container_name: 77sol-php
    build:
      context: .
      dockerfile: ./docker/phpfpm.docker
    image: dev/php
    ports:
      - '9001:9000'
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    restart: always

  db:
    container_name: 77sol-mysql
    image: mysql:5.7
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}